
#include <vector>
#include <string>

using namespace std;

#include "png_converted.h"

std::vector<PNG> png_array;

void init_png_array(void)
{	
	// the following code in this function was generated by VideoGamePngConverter ...

/*[MARKER_FOR_ASSETS]*/
}

int get_png(vector<unsigned char>* image, unsigned* w, unsigned* h, string sprite_path)
{
	
	// search for entry in png array
	for(int i = 0; i < png_array.size(); i++)
	{
		
		// get filename of sprite
		int pos = sprite_path.find_last_of("/");
		string sprite_file = sprite_path.substr(pos + 1, sprite_file.length() - pos - 1);

		// compare names
		if(png_array.at(i).png_name == sprite_file)
		{
			// set point to image data and return
			*w = png_array.at(i).w;
			*h = png_array.at(i).h;
			*image = png_array.at(i).vector_array;
			return 0;
		}
	}

	// png not found
	*w = 0;
	*h = 0;
	return 1;
}
